// List compiled from https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/aa563041(v=exchg.140)
export const emailContentTypes = [
  'application/cals-1840',
  'application/marc',
  'application/news-message-id',
  'application/news-transmission',
  'application/octet-stream',
  'application/oda',
  'application/pgp-encrypted',
  'application/pgp-keys',
  'application/pgp-signature',
  'application/pkcs7-MIME',
  'application/pkcs7-signature',
  'application/pkcs10',
  'application/postscript',
  'application/remote-printing',
  'application/sgml',
  'application/x400-bp',
  'audio/32kadpcm',
  'audio/basic',
  'image/g3fax',
  'image/gif',
  'image/ief',
  'image/jpeg',
  'image/tiff',
  'message/delivery-status',
  'message/disposition-notification-to',
  'message/external-body',
  'message/http',
  'message/partial',
  'message/rfc822',
  'multipart/alternative', // Common
  'multipart/byteranges',
  'multipart/digest',
  'multipart/form-data',
  'multipart/mixed', // Common
  'multipart/parallel',
  'multipart/related',
  'text/enriched',
  'text/html',
  'text/plain',
  'text/rfc822-headers',
  'text/richtext',
  'text/sgml',
  'video/mpeg',
] as const;

export type ContentType = typeof emailContentTypes[number];
